name: CI

on:
  workflow_dispatch:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - image: ubuntu-latest
            generator: Ninja
            build_type: Release
          - image: windows-latest
            generator: Visual Studio 17 2022
            build_type: Release
          - image: macos-latest
            generator: Ninja
            build_type: Release
    runs-on: ${{ matrix.image }}
    steps:
      - uses: actions/checkout@v4

      - name: Configure
        run: cmake -S . -B build -G "${{ matrix.generator }}" -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} -DLIBSTREAM_POST_BUILD_UNITTEST=ON -DCMAKE_POLICY_VERSION_MINIMUM=3.5

      - name: Build
        run: cmake --build build --config ${{ matrix.build_type }} --parallel

      - name: Test
        run: ctest --test-dir build --build-config ${{ matrix.build_type }} --output-on-failure
